export const N = [
  { k: 'cal', label: 'Calories', u: '', t: null, grp: 'Macros' },
  { k: 'protein', label: 'Protein', u: 'g', t: 75, grp: 'Macros' },
  { k: 'collagen', label: 'Collagen', u: 'g', t: null, grp: 'Macros' },
  { k: 'fiber', label: 'Fiber', u: 'g', t: 25, grp: 'Macros' },
  { k: 'fat', label: 'Fat', u: 'g', t: null, grp: 'Macros' },
  { k: 'satfat', label: 'Saturated fat', u: 'g', t: null, grp: 'Macros' },
  { k: 'carbs', label: 'Total carbs', u: 'g', t: null, grp: 'Macros' },
  { k: 'netcarbs', label: 'Net carbs (keto)', u: 'g', t: null, grp: 'Macros' },
  { k: 'sugar', label: 'Sugar', u: 'g', t: null, grp: 'Macros' },
  { k: 'vitA', label: 'Vitamin A', u: 'mcg', t: 700, ul: 3000, grp: 'Fat-soluble vitamins' },
  { k: 'vitD', label: 'Vitamin D', u: 'IU', t: 600, ul: 4000, grp: 'Fat-soluble vitamins' },
  { k: 'vitE', label: 'Vitamin E', u: 'mg', t: 15, ul: 1000, grp: 'Fat-soluble vitamins' },
  { k: 'vitK', label: 'Vitamin K', u: 'mcg', t: 90, grp: 'Fat-soluble vitamins' },
  { k: 'vitC', label: 'Vitamin C', u: 'mg', t: 75, ul: 2000, grp: 'Water-soluble vitamins' },
  { k: 'b1', label: 'B1 Thiamine', u: 'mg', t: 1.1, grp: 'Water-soluble vitamins' },
  { k: 'b2', label: 'B2 Riboflavin', u: 'mg', t: 1.1, grp: 'Water-soluble vitamins' },
  { k: 'b3', label: 'B3 Niacin', u: 'mg', t: 14, grp: 'Water-soluble vitamins' },
  { k: 'b5', label: 'B5 Pantothenic', u: 'mg', t: 5, grp: 'Water-soluble vitamins' },
  { k: 'b6', label: 'B6', u: 'mg', t: 1.3, ul: 100, grp: 'Water-soluble vitamins' },
  { k: 'b7', label: 'B7 Biotin', u: 'mcg', t: 30, grp: 'Water-soluble vitamins' },
  { k: 'folate', label: 'Folate', u: 'mcg', t: 400, ul: 1000, grp: 'Water-soluble vitamins' },
  { k: 'b12', label: 'B12', u: 'mcg', t: 2.4, grp: 'Water-soluble vitamins' },
  { k: 'calcium', label: 'Calcium', u: 'mg', t: 1000, ul: 2500, grp: 'Major minerals' },
  { k: 'magnesium', label: 'Magnesium', u: 'mg', t: 320, grp: 'Major minerals' },
  { k: 'phosphorus', label: 'Phosphorus', u: 'mg', t: 700, grp: 'Major minerals' },
  { k: 'potassium', label: 'Potassium', u: 'mg', t: 2600, grp: 'Major minerals' },
  { k: 'sodium', label: 'Sodium', u: 'mg', t: 1500, ul: 2300, grp: 'Major minerals' },
  { k: 'iron', label: 'Iron', u: 'mg', t: 18, ul: 45, grp: 'Trace minerals' },
  { k: 'zinc', label: 'Zinc', u: 'mg', t: 8, ul: 40, grp: 'Trace minerals' },
  { k: 'copper', label: 'Copper', u: 'mcg', t: 900, ul: 10000, grp: 'Trace minerals' },
  { k: 'selenium', label: 'Selenium', u: 'mcg', t: 55, ul: 400, grp: 'Trace minerals' },
  { k: 'iodine', label: 'Iodine', u: 'mcg', t: 150, ul: 1100, grp: 'Trace minerals' },
  { k: 'manganese', label: 'Manganese', u: 'mg', t: 1.8, ul: 11, grp: 'Trace minerals' },
  { k: 'chromium', label: 'Chromium', u: 'mcg', t: 25, grp: 'Trace minerals' },
  { k: 'omega3', label: 'Omega-3 EPA/DHA', u: 'mg', t: 300, grp: 'Fats & other' },
  { k: 'choline', label: 'Choline', u: 'mg', t: 425, ul: 3500, grp: 'Fats & other' },
];

function I(id, name, cat, serving, nut, note) { return { id, name, cat, serving, nut, note }; }

export const LIB = [
  I('breakfast', 'Breakfast — 2 eggs + spinach + salt', 'meal', 'daily', { cal: 250, protein: 13, fat: 10, satfat: 3.1, carbs: 1.8, netcarbs: 1.1, sugar: 0.5, choline: 290, selenium: 35, b7: 22, b2: 0.5, vitA: 300, vitK: 145, folate: 100, b12: 1.1, iodine: 50, magnesium: 24, zinc: 1.3, iron: 2, vitC: 8, vitD: 80, vitE: 1, b5: 1.5, phosphorus: 220, calcium: 40, potassium: 170, sodium: 300 }),
  I('tuna', 'Lunch — tuna + celery + mayo', 'meal', '~5oz can', { cal: 320, protein: 31, fat: 17, satfat: 3.3, carbs: 1.5, netcarbs: 0.9, sugar: 1, selenium: 120, b12: 4, b3: 18, b6: 0.5, omega3: 250, vitD: 60, phosphorus: 180, potassium: 460, vitK: 35, folate: 36, vitE: 2, magnesium: 30, vitC: 9, iron: 1.3, zinc: 0.8, iodine: 15 }),
  I('quinoa', 'Dinner — quinoa + arugula + tomato', 'meal', '1.5 cups', { cal: 480, protein: 14, fat: 17, satfat: 0.7, carbs: 68, netcarbs: 59, sugar: 4, fiber: 9, magnesium: 185, manganese: 1.9, phosphorus: 440, copper: 500, folate: 155, potassium: 840, iron: 4.5, zinc: 3, vitC: 23, vitK: 25, b1: 0.3, vitE: 3, vitA: 30, calcium: 60 }),
  I('matcha', 'Matcha', 'drink', '1 tbsp', { cal: 4, carbs: 0.8, netcarbs: 0.3, vitK: 60, potassium: 40, magnesium: 4, manganese: 0.03, zinc: 0.03, iron: 0.25 }),
  I('beam', 'BEAM (Electrolyze + Micro-Boost)', 'drink', '1 dose', { magnesium: 5, potassium: 10 }, 'trace minerals'),
  I('thorneamino', 'Thorne Amino Complex', 'drink', '1 scoop', { cal: 25, protein: 4, carbs: 1, netcarbs: 1 }),
  I('broth', 'Bone broth', 'drink', '16 oz', { cal: 80, protein: 20, satfat: 0.5, carbs: 1, netcarbs: 1, collagen: 14, sodium: 600, potassium: 120, phosphorus: 40, calcium: 15, magnesium: 10, b12: 0.2, folate: 3 }),
  I('berg', 'Dr. Berg electrolytes', 'drink', '1 scoop', { cal: 15, carbs: 3, netcarbs: 2, potassium: 1000, magnesium: 120, calcium: 75, sodium: 40, iron: 0.3 }),
  I('pellegrino', 'San Pellegrino', 'drink', '1 L', { calcium: 150, magnesium: 45, sodium: 31, potassium: 2 }),
  I('egg', 'Egg', 'protein', '1 large', { cal: 72, protein: 6, fat: 5, satfat: 1.6, carbs: 0.4, netcarbs: 0.4, sugar: 0.2, choline: 147, selenium: 15, b7: 10, b2: 0.23, vitA: 80, vitD: 41, b12: 0.55, folate: 22, iodine: 25, phosphorus: 99, calcium: 28, zinc: 0.65, iron: 0.9, b5: 0.7 }),
  I('oysters', 'Oysters', 'protein', '3 oz', { cal: 70, protein: 8, satfat: 0.5, carbs: 4, netcarbs: 4, zinc: 32, copper: 1600, selenium: 64, b12: 16, iron: 5, iodine: 50, omega3: 300, choline: 60 }),
  I('liver', 'Beef liver', 'protein', '3 oz', { cal: 130, protein: 20, satfat: 1.5, carbs: 4, netcarbs: 4, vitA: 6500, copper: 12000, b12: 60, folate: 215, iron: 5, b2: 2.9, choline: 330, selenium: 28, zinc: 4 }),
  I('beef', 'Grass-fed beef', 'protein', '8 oz', { cal: 430, protein: 52, fat: 24, satfat: 10, zinc: 11, iron: 5, b12: 5, b3: 12, selenium: 40, phosphorus: 400, potassium: 600, choline: 150 }),
  I('salmon', 'Wild salmon', 'protein', '6 oz', { cal: 310, protein: 34, fat: 18, satfat: 3, omega3: 3000, vitD: 1000, b12: 5, selenium: 46, b3: 16, potassium: 800, choline: 100 }),
  I('sardines', 'Sardines', 'protein', '1 can', { cal: 190, protein: 23, fat: 11, satfat: 1.5, calcium: 350, omega3: 1000, vitD: 180, b12: 8, selenium: 45, phosphorus: 280 }),
  I('shrimp', 'Shrimp', 'protein', '3 oz', { cal: 85, protein: 20, satfat: 0.1, carbs: 0.2, netcarbs: 0.2, selenium: 34, iodine: 35, copper: 200, b12: 1.4, iron: 0.5, zinc: 1.4 }),
  I('chicken', 'Chicken thigh', 'protein', '4 oz', { cal: 220, protein: 25, fat: 13, satfat: 3.5, b6: 0.4, b3: 7, selenium: 25, zinc: 2, phosphorus: 200, potassium: 250 }),
  I('spinach', 'Spinach', 'veg', '1 cup', { carbs: 1.1, netcarbs: 0.4, sugar: 0.1, fiber: 0.7, vitK: 145, folate: 58, vitA: 140, vitC: 8, magnesium: 24, iron: 0.8, potassium: 167, calcium: 30, manganese: 0.27 }),
  I('broccoli', 'Broccoli', 'veg', '1 cup', { cal: 55, carbs: 11, netcarbs: 6, sugar: 2, vitC: 81, vitK: 92, folate: 57, fiber: 5, calcium: 43, potassium: 290, vitA: 35 }),
  I('kale', 'Kale', 'veg', '1 cup', { carbs: 1.4, netcarbs: 0.5, sugar: 0.2, vitK: 472, vitC: 80, vitA: 170, folate: 19, calcium: 53, manganese: 0.5 }),
  I('bellpepper', 'Bell pepper', 'veg', '1 medium', { cal: 30, carbs: 7, netcarbs: 4.5, sugar: 5, vitC: 152, vitA: 75, folate: 46, b6: 0.4, potassium: 250, fiber: 2.5 }),
  I('sweetpotato', 'Sweet potato', 'veg', '1 medium', { cal: 112, carbs: 26, netcarbs: 22, sugar: 5.4, vitA: 1400, vitC: 22, b6: 0.3, potassium: 440, fiber: 4, manganese: 0.5 }),
  I('avocado', 'Avocado', 'fat', '½', { cal: 160, fat: 15, satfat: 2.1, carbs: 9, netcarbs: 4, sugar: 0.4, fiber: 5, potassium: 345, magnesium: 29, vitE: 2, folate: 60, vitK: 14 }),
  I('blueberries', 'Blueberries', 'fruit', '1 cup', { cal: 85, carbs: 21, netcarbs: 17, sugar: 15, vitC: 14, vitK: 29, fiber: 4, manganese: 0.5 }),
  I('almonds', 'Almonds', 'fat', '1 oz', { cal: 164, protein: 6, fat: 14, satfat: 1.1, carbs: 6, netcarbs: 2.5, sugar: 1.2, vitE: 7, magnesium: 76, calcium: 76, fiber: 3.5 }),
  I('brazilnut', 'Brazil nut', 'fat', '1 nut', { cal: 33, satfat: 0.8, carbs: 0.3, netcarbs: 0.1, sugar: 0.1, selenium: 96, magnesium: 25 }, 'very high selenium'),
  I('oliveoil', 'Olive oil', 'fat', '1 tbsp', { cal: 120, fat: 14, satfat: 1.9, vitE: 2, vitK: 8 }),
  I('kefir', 'Kefir', 'dairy', '1 cup', { cal: 110, protein: 9, satfat: 1.5, carbs: 12, netcarbs: 12, sugar: 11, calcium: 300, b12: 1, phosphorus: 230, potassium: 376 }),
  I('cheese', 'Hard cheese', 'dairy', '1 oz', { cal: 110, protein: 7, satfat: 5.3, carbs: 0.4, netcarbs: 0.4, sugar: 0.1, calcium: 200, fat: 9, b12: 0.4 }),
  I('chickenliver', 'Chicken liver', 'protein', '3 oz', { cal: 142, protein: 21, fat: 6, satfat: 1.9, carbs: 1, netcarbs: 1, vitA: 3980, vitC: 23, b2: 1.5, b3: 9, b5: 5, b6: 0.6, b7: 150, folate: 490, b12: 14, iron: 9, zinc: 3.4, copper: 400, selenium: 70, phosphorus: 340, potassium: 230, choline: 220 }),
  I('beefheart', 'Beef heart', 'protein', '3 oz', { cal: 150, protein: 24, fat: 5, satfat: 1.5, b2: 1.1, b3: 6, b5: 2, b6: 0.3, b12: 11, iron: 6, zinc: 3, copper: 500, selenium: 35, phosphorus: 230, potassium: 210, choline: 135 }),
  I('mackerel', 'Atlantic mackerel', 'protein', '3 oz', { cal: 220, protein: 20, fat: 15, satfat: 3.6, vitD: 340, b12: 16, b3: 6, b6: 0.4, selenium: 44, phosphorus: 236, potassium: 340, magnesium: 83, iron: 1.3, omega3: 1000, choline: 80 }),
  I('cod', 'Cod', 'protein', '3 oz', { cal: 90, protein: 20, fat: 0.7, satfat: 0.1, b12: 1.8, b6: 0.4, selenium: 32, iodine: 99, phosphorus: 117, potassium: 210, omega3: 150 }),
  I('mussels', 'Mussels', 'protein', '3 oz', { cal: 146, protein: 20, fat: 4, satfat: 0.8, carbs: 6, netcarbs: 6, vitC: 12, b2: 0.4, b3: 2.6, b12: 20, folate: 64, iron: 5.7, zinc: 2.3, manganese: 5.8, selenium: 64, phosphorus: 242, potassium: 228, omega3: 700, choline: 65 }),
  I('scallops', 'Scallops', 'protein', '3 oz', { cal: 94, protein: 17, fat: 1.2, satfat: 0.1, carbs: 4, netcarbs: 4, b12: 1.5, phosphorus: 340, potassium: 310, magnesium: 47, selenium: 22, zinc: 1.4, omega3: 300 }),
  I('cauliflower', 'Cauliflower', 'veg', '1 cup', { cal: 27, protein: 2, fat: 0.3, carbs: 5, netcarbs: 3, fiber: 2, sugar: 2, vitC: 52, vitK: 16, folate: 61, b6: 0.2, potassium: 320, choline: 45 }),
  I('zucchini', 'Zucchini', 'veg', '1 cup', { cal: 21, protein: 1.5, fat: 0.4, carbs: 4, netcarbs: 2.6, fiber: 1.4, sugar: 3, vitC: 22, vitA: 24, b6: 0.3, potassium: 325, manganese: 0.2 }),
  I('asparagus', 'Asparagus', 'veg', '1 cup', { cal: 40, protein: 4.3, fat: 0.4, satfat: 0.1, carbs: 7, netcarbs: 3.4, fiber: 3.6, sugar: 2.3, vitK: 91, folate: 268, vitC: 14, vitA: 90, vitE: 2.7, b1: 0.3, iron: 1.6, potassium: 400 }),
  I('brusselssprouts', 'Brussels sprouts', 'veg', '1 cup', { cal: 56, protein: 4, fat: 0.8, satfat: 0.2, carbs: 11, netcarbs: 7, fiber: 4, sugar: 2.7, vitC: 97, vitK: 219, folate: 94, vitA: 60, potassium: 495, manganese: 0.4 }),
  I('cabbage', 'Cabbage', 'veg', '1 cup', { cal: 22, protein: 1.1, fat: 0.1, carbs: 5, netcarbs: 2.8, fiber: 2.2, sugar: 2.8, vitC: 33, vitK: 68, folate: 38, potassium: 150 }),
  I('arugula', 'Arugula', 'veg', '1 cup', { cal: 5, protein: 0.5, fat: 0.1, carbs: 0.7, netcarbs: 0.4, fiber: 0.3, sugar: 0.4, vitK: 22, vitA: 24, folate: 19, vitC: 3, calcium: 32, potassium: 74 }),
  I('mushrooms', 'White mushrooms', 'veg', '1 cup', { cal: 15, protein: 2.2, fat: 0.2, carbs: 2.3, netcarbs: 1.6, fiber: 0.7, sugar: 1.4, vitD: 5, b2: 0.3, b3: 2.5, b5: 1, selenium: 8, copper: 220, potassium: 220 }),
  I('greenbeans', 'Green beans', 'veg', '1 cup', { cal: 44, protein: 2.4, fat: 0.4, satfat: 0.1, carbs: 10, netcarbs: 6, fiber: 4, sugar: 2, vitC: 12, vitK: 60, folate: 42, vitA: 44, potassium: 180, manganese: 0.5 }),
  I('sauerkraut', 'Sauerkraut', 'veg', '½ cup', { cal: 14, protein: 0.7, fat: 0.1, carbs: 3, netcarbs: 1, fiber: 2, sugar: 1.3, vitC: 10, vitK: 9, folate: 12, iron: 1.2, potassium: 120, sodium: 470 }),
  I('kimchi', 'Kimchi', 'veg', '½ cup', { cal: 12, protein: 1, fat: 0.2, carbs: 2, netcarbs: 1, fiber: 1, sugar: 1, vitC: 10, vitK: 24, vitA: 80, folate: 35, potassium: 150, sodium: 500 }, 'sodium varies by recipe'),
  I('yogurt', 'Full-fat plain yogurt', 'dairy', '1 cup', { cal: 150, protein: 8.5, fat: 8, satfat: 5, carbs: 11, netcarbs: 11, sugar: 11, calcium: 296, phosphorus: 233, potassium: 380, b2: 0.3, b12: 1, zinc: 1.4, iodine: 75, choline: 38 }),
  I('macadamia', 'Macadamia nuts', 'fat', '1 oz', { cal: 204, protein: 2.2, fat: 21, satfat: 3.4, carbs: 4, netcarbs: 1.5, fiber: 2.5, sugar: 1.2, b1: 0.3, manganese: 1.2, magnesium: 37, copper: 270, potassium: 104, iron: 1 }),
  I('walnuts', 'Walnuts', 'fat', '1 oz', { cal: 185, protein: 4.3, fat: 18, satfat: 1.7, carbs: 4, netcarbs: 2, fiber: 2, sugar: 0.7, copper: 450, manganese: 1, magnesium: 45, phosphorus: 98, folate: 28 }, 'plant omega-3 (ALA)'),
  I('pecans', 'Pecans', 'fat', '1 oz', { cal: 196, protein: 2.6, fat: 20, satfat: 1.8, carbs: 4, netcarbs: 1.2, fiber: 2.7, sugar: 1.1, manganese: 1.3, copper: 340, zinc: 1.3, magnesium: 34, b1: 0.2 }),
  I('chiaseeds', 'Chia seeds', 'fat', '1 oz', { cal: 138, protein: 5, fat: 9, satfat: 1, carbs: 12, netcarbs: 2, fiber: 10, calcium: 179, magnesium: 95, phosphorus: 244, iron: 2.2, zinc: 1.3, manganese: 0.8 }, 'plant omega-3 (ALA)'),
  I('flaxseeds', 'Ground flaxseed', 'fat', '2 tbsp', { cal: 75, protein: 2.6, fat: 6, satfat: 0.5, carbs: 4, netcarbs: 0.5, fiber: 3.8, sugar: 0.2, magnesium: 55, phosphorus: 90, potassium: 120, b1: 0.2, manganese: 0.4, copper: 170 }, 'plant omega-3 (ALA)'),
  I('pumpkinseeds', 'Pumpkin seeds', 'fat', '1 oz', { cal: 151, protein: 7, fat: 13, satfat: 2.3, carbs: 5, netcarbs: 3.2, fiber: 1.8, sugar: 0.4, magnesium: 150, zinc: 2.2, iron: 2.3, phosphorus: 330, manganese: 1.3, copper: 390, potassium: 260 }),
  I('mctoil', 'MCT oil', 'fat', '1 tbsp', { cal: 115, fat: 14, satfat: 14 }),
  I('coconutoil', 'Coconut oil', 'fat', '1 tbsp', { cal: 120, fat: 14, satfat: 12 }),
  I('ghee', 'Ghee', 'fat', '1 tbsp', { cal: 123, fat: 14, satfat: 9, vitA: 108, vitE: 0.4 }),
  I('butter', 'Butter', 'fat', '1 tbsp', { cal: 102, protein: 0.1, fat: 12, satfat: 7, vitA: 97, vitD: 6, vitE: 0.3, vitK: 1 }),
  I('raspberries', 'Raspberries', 'fruit', '1 cup', { cal: 64, protein: 1.5, fat: 0.8, carbs: 15, netcarbs: 7, fiber: 8, sugar: 5, vitC: 32, vitK: 10, folate: 26, manganese: 0.8, magnesium: 27, potassium: 186 }),
  I('strawberries', 'Strawberries', 'fruit', '1 cup', { cal: 53, protein: 1.1, fat: 0.5, carbs: 13, netcarbs: 9.5, fiber: 3.3, sugar: 8, vitC: 98, folate: 40, manganese: 0.6, potassium: 254 }),
  I('blackberries', 'Blackberries', 'fruit', '1 cup', { cal: 62, protein: 2, fat: 0.7, carbs: 14, netcarbs: 6.2, fiber: 7.6, sugar: 7, vitC: 30, vitK: 29, folate: 36, manganese: 0.9, magnesium: 29, potassium: 233 }),
  I('salt', 'Salt', 'extra', 'pinch', { sodium: 300 }),
];

export const STACK = [
  I('multi', 'Thorne Basic Nutrients 2/Day', 'sup', 'multivitamin', { vitA: 1050, vitC: 250, vitD: 2000, vitE: 16.5, vitK: 400, b1: 50, b2: 12, b3: 20, b5: 90, b6: 10, b7: 400, folate: 400, b12: 3, zinc: 15, copper: 450, selenium: 200, iodine: 225, manganese: 2, chromium: 100, calcium: 52, magnesium: 40 }),
  I('dake', 'Suppgrade DAKE (D/A/K/E)', 'sup', 'fat-solubles', { vitD: 5000, vitA: 1515, vitE: 50, vitK: 300 }),
  I('omega', 'Omega 2000 fish oil', 'sup', '875 DHA', { omega3: 2000 }),
  I('bufferedc', 'Buffered Vitamin C', 'sup', 'Integrative', { vitC: 500 }),
  I('puremelt', 'PureMelt B12 + Folate', 'sup', 'Pure Encaps', { carbs: 0.5, netcarbs: 0.5, sugar: 0.5, folate: 400, b12: 1000 }),
  I('rhomag', 'Magnesium (Rho)', 'sup', '1 dose', { magnesium: 300 }),
  I('chromium', 'Chromium picolinate', 'sup', '1 dose', { chromium: 200 }),
  I('neurotopical', 'Methylation Pro Topical', 'sup', 'Neuro Biologix', {}, 'methylation support'),
  I('fatty15', 'Fatty15 (C15:0)', 'sup', '1 cap', {}, 'no charted nutrients'),
  I('glycine', 'Glycine', 'sup', 'Pure Encaps', {}, 'no charted nutrients'),
  I('nac', 'NAC 500mg', 'sup', 'Seeking Health', {}, 'no charted nutrients'),
  I('ubqh', 'UBQH / CoQ10 100mg', 'sup', 'Integrative', {}, 'no charted nutrients'),
  I('lithium', 'Lithium orotate 5mg', 'sup', 'Vital Nutrients', {}, 'no charted nutrients'),
  I('p3om', 'P3-OM probiotic', 'sup', 'BiOptimizers', {}, 'no charted nutrients'),
  I('regenx', 'REGEN-X', 'sup', 'PureLife', {}, 'no charted nutrients'),
];

export const ALLMAP = {};
[...LIB, ...STACK].forEach((it) => { ALLMAP[it.id] = it; });

// Standard daily dose per supplement (units + word). Nutrients scale by (taken / caps).
export const DOSE = {
  multi: { caps: 2, unit: 'capsules' },
  dake: { caps: 1, unit: 'capsules' },
  omega: { caps: 2, unit: 'softgels' },
  bufferedc: { caps: 1, unit: 'capsule' },
  puremelt: { caps: 1, unit: 'melt' },
  rhomag: { caps: 1, unit: 'capsule' },
  chromium: { caps: 1, unit: 'capsule' },
  neurotopical: { caps: 1, unit: 'topical' },
  fatty15: { caps: 1, unit: 'capsule' },
  glycine: { caps: 1, unit: 'capsule' },
  nac: { caps: 1, unit: 'capsule' },
  ubqh: { caps: 1, unit: 'softgel' },
  lithium: { caps: 1, unit: 'capsule' },
  p3om: { caps: 2, unit: 'capsules' },
  regenx: { caps: 1, unit: 'drops' },
};

export const MOOD_LEVELS = [
  { id: 'sinking', label: 'Sinking', color: '#3D5CA8', med: '#C6CFEA' },
  { id: 'low', label: 'Heavy', color: '#7E92D8', med: '#D9DFF4' },
  { id: 'level', label: 'Even', color: '#2FA97C', med: '#BFE6D3' },
  { id: 'lifted', label: 'Rising', color: '#E2A02C', med: '#F2E0AC' },
  { id: 'racing', label: 'Racing', color: '#DA5348', med: '#F3CBC4' },
];
export const MOOD_MAP = Object.fromEntries(MOOD_LEVELS.map((m) => [m.id, m]));

export const ENERGY_LEVELS = [
  { id: 'low', label: 'Running low' },
  { id: 'steady', label: 'Steady' },
  { id: 'buzzing', label: 'Buzzing' },
];

export const SLEEP_HRS = [
  { id: 'u4', label: 'Under 4' },
  { id: '4_6', label: '4–6' },
  { id: '6_8', label: '6–8' },
  { id: '8p', label: '8+' },
];
export const SLEEP_FELT = [
  { id: 'rested', label: 'Rested' },
  { id: 'deep', label: 'Deep' },
  { id: 'light', label: 'Light' },
  { id: 'restless', label: 'Restless' },
  { id: 'woke', label: 'Woke a lot' },
  { id: 'wired', label: 'Wired' },
  { id: 'couldnt', label: "Couldn't wind down" },
  { id: 'groggy', label: 'Groggy' },
  { id: 'dreams', label: 'Vivid dreams' },
];

export const TANK_LEVELS = [
  { id: 'roomy', label: 'Roomy' },
  { id: 'full', label: 'Full' },
  { id: 'toomuch', label: 'Too much' },
];

export const MOODS = [
  { id: 'calm', label: 'Calm' },
  { id: 'grounded', label: 'Grounded' },
  { id: 'connected', label: 'Connected' },
  { id: 'content', label: 'Content' },
  { id: 'clear', label: 'Clear' },
  { id: 'good', label: 'Good' },
  { id: 'hopeful', label: 'Hopeful' },
  { id: 'numb', label: 'Numb' },
  { id: 'anxious', label: 'Anxious' },
  { id: 'irritable', label: 'Irritable' },
  { id: 'overwhelmed', label: 'Overwhelmed' },
  { id: 'foggy', label: 'Foggy' },
  { id: 'restless', label: 'Restless' },
];

export const HABITS = [
  { id: 'sun_am', label: 'Morning sunlight', grp: 'daily' },
  { id: 'sun_pm', label: 'Afternoon sunlight', grp: 'daily' },
  { id: 'sunset', label: 'Sunset', grp: 'daily' },
  { id: 'redlight', label: 'Red light', grp: 'daily' },
  { id: 'sauna', label: 'Sauna', grp: 'daily' },
  { id: 'cold_plunge', label: 'Cold plunge', grp: 'daily' },
  { id: 'grounding', label: 'Grounding', grp: 'daily' },
  { id: 'no_toxins', label: 'No toxic chemicals', grp: 'daily' },
  { id: 'floss', label: 'Flossing', grp: 'daily' },
  { id: 'waterpik', label: 'Water pick', grp: 'daily' },
  { id: 'journal', label: 'Aesthetic journaling', grp: 'daily' },
  { id: 'labs', label: 'Labs', note: 'once a year', grp: 'occasional' },
  { id: 'hair_color', label: 'Hair coloring', note: '3–4× a year', grp: 'occasional' },
];
