export const N = [
  { k: 'cal', label: 'Calories', u: '', t: null, grp: 'Macros' },
  { k: 'protein', label: 'Protein', u: 'g', t: 75, grp: 'Macros' },
  { k: 'collagen', label: 'Collagen', u: 'g', t: null, grp: 'Macros' },
  { k: 'fiber', label: 'Fiber', u: 'g', t: 25, grp: 'Macros' },
  { k: 'fat', label: 'Fat', u: 'g', t: null, grp: 'Macros' },
  { k: 'satfat', label: 'Saturated fat', u: 'g', t: null, grp: 'Macros' },
  { k: 'carbs', label: 'Total carbs', u: 'g', t: null, grp: 'Macros' },
  { k: 'netcarbs', label: 'Net carbs (keto)', u: 'g', t: null, grp: 'Macros' },
  { k: 'sugar', label: 'Sugar', u: 'g', t: null, grp: 'Macros' },
  { k: 'vitA', label: 'Vitamin A', u: 'mcg', t: 700, ul: 3000, grp: 'Fat-soluble vitamins' },
  { k: 'vitD', label: 'Vitamin D', u: 'IU', t: 600, ul: 4000, grp: 'Fat-soluble vitamins' },
  { k: 'vitE', label: 'Vitamin E', u: 'mg', t: 15, ul: 1000, grp: 'Fat-soluble vitamins' },
  { k: 'vitK', label: 'Vitamin K', u: 'mcg', t: 90, grp: 'Fat-soluble vitamins' },
  { k: 'vitC', label: 'Vitamin C', u: 'mg', t: 75, ul: 2000, grp: 'Water-soluble vitamins' },
  { k: 'b1', label: 'B1 Thiamine', u: 'mg', t: 1.1, grp: 'Water-soluble vitamins' },
  { k: 'b2', label: 'B2 Riboflavin', u: 'mg', t: 1.1, grp: 'Water-soluble vitamins' },
  { k: 'b3', label: 'B3 Niacin', u: 'mg', t: 14, grp: 'Water-soluble vitamins' },
  { k: 'b5', label: 'B5 Pantothenic', u: 'mg', t: 5, grp: 'Water-soluble vitamins' },
  { k: 'b6', label: 'B6', u: 'mg', t: 1.3, ul: 100, grp: 'Water-soluble vitamins' },
  { k: 'b7', label: 'B7 Biotin', u: 'mcg', t: 30, grp: 'Water-soluble vitamins' },
  { k: 'folate', label: 'Folate', u: 'mcg', t: 400, ul: 1000, grp: 'Water-soluble vitamins' },
  { k: 'b12', label: 'B12', u: 'mcg', t: 2.4, grp: 'Water-soluble vitamins' },
  { k: 'calcium', label: 'Calcium', u: 'mg', t: 1000, ul: 2500, grp: 'Major minerals' },
  { k: 'magnesium', label: 'Magnesium', u: 'mg', t: 320, grp: 'Major minerals' },
  { k: 'phosphorus', label: 'Phosphorus', u: 'mg', t: 700, grp: 'Major minerals' },
  { k: 'potassium', label: 'Potassium', u: 'mg', t: 2600, grp: 'Major minerals' },
  { k: 'sodium', label: 'Sodium', u: 'mg', t: 1500, ul: 2300, grp: 'Major minerals' },
  { k: 'iron', label: 'Iron', u: 'mg', t: 18, ul: 45, grp: 'Trace minerals' },
  { k: 'zinc', label: 'Zinc', u: 'mg', t: 8, ul: 40, grp: 'Trace minerals' },
  { k: 'copper', label: 'Copper', u: 'mcg', t: 900, ul: 10000, grp: 'Trace minerals' },
  { k: 'selenium', label: 'Selenium', u: 'mcg', t: 55, ul: 400, grp: 'Trace minerals' },
  { k: 'iodine', label: 'Iodine', u: 'mcg', t: 150, ul: 1100, grp: 'Trace minerals' },
  { k: 'manganese', label: 'Manganese', u: 'mg', t: 1.8, ul: 11, grp: 'Trace minerals' },
  { k: 'chromium', label: 'Chromium', u: 'mcg', t: 25, grp: 'Trace minerals' },
  { k: 'omega3', label: 'Omega-3 EPA/DHA', u: 'mg', t: 300, grp: 'Fats & other' },
  { k: 'choline', label: 'Choline', u: 'mg', t: 425, ul: 3500, grp: 'Fats & other' },
];

function I(id, name, cat, serving, nut, note) { return { id, name, cat, serving, nut, note }; }

export const LIB = [
  I('breakfast', 'Breakfast — 2 eggs + spinach + salt', 'meal', 'daily', { cal: 250, protein: 13, fat: 10, satfat: 3.1, carbs: 1.8, netcarbs: 1.1, sugar: 0.5, choline: 290, selenium: 35, b7: 22, b2: 0.5, vitA: 300, vitK: 145, folate: 100, b12: 1.1, iodine: 50, magnesium: 24, zinc: 1.3, iron: 2, vitC: 8, vitD: 80, vitE: 1, b5: 1.5, phosphorus: 220, calcium: 40, potassium: 170, sodium: 300 }),
  I('tuna', 'Lunch — tuna + celery + mayo', 'meal', '~5oz can', { cal: 320, protein: 31, fat: 17, satfat: 3.3, carbs: 1.5, netcarbs: 0.9, sugar: 1, selenium: 120, b12: 4, b3: 18, b6: 0.5, omega3: 250, vitD: 60, phosphorus: 180, potassium: 460, vitK: 35, folate: 36, vitE: 2, magnesium: 30, vitC: 9, iron: 1.3, zinc: 0.8, iodine: 15 }),
  I('quinoa', 'Dinner — quinoa + arugula + tomato', 'meal', '¾ cup quinoa · handful arugula · ⅓ tomato', { cal: 300, protein: 7, fat: 17, satfat: 2, carbs: 32, netcarbs: 28, sugar: 2, fiber: 4.5, magnesium: 70, manganese: 1, phosphorus: 150, copper: 250, folate: 80, potassium: 410, iron: 2.5, zinc: 1.5, vitC: 8, vitK: 33, b1: 0.15, vitE: 2.6, vitA: 41, calcium: 40 }),
  I('kwaffle', 'Keto waffle (almond)', 'meal', '1 waffle', { cal: 388, protein: 14, fat: 34, satfat: 8, carbs: 9, netcarbs: 4.3, sugar: 2.4, fiber: 5, vitE: 12, magnesium: 135, calcium: 147, choline: 150, b2: 0.6, manganese: 1, selenium: 17, b12: 0.6, phosphorus: 200, vitA: 130, iron: 1.8, potassium: 259 }, 'almond flour · egg · butter · milk'),
  I('cwaffle', 'Keto waffle (coconut)', 'meal', '1 waffle', { cal: 285, protein: 11, fat: 23, satfat: 14, carbs: 8, netcarbs: 3, sugar: 2, fiber: 5, choline: 210, selenium: 23, b12: 0.8, vitA: 180, b2: 0.4, iron: 1.6, magnesium: 25, vitE: 1 }, 'coconut flour · egg · butter · coconut milk'),
  I('matcha', 'Matcha', 'drink', '1 tbsp', { cal: 4, carbs: 0.8, netcarbs: 0.3, vitK: 60, potassium: 40, magnesium: 4, manganese: 0.03, zinc: 0.03, iron: 0.25 }),
  I('beam', 'BEAM (Electrolyze + Micro-Boost)', 'drink', '1 dose', { magnesium: 5, potassium: 10 }, 'trace minerals'),
  I('thorneamino', 'Thorne Amino Complex', 'drink', '1 scoop', { cal: 25, protein: 4, carbs: 1, netcarbs: 1 }),
  I('broth', 'Bone broth', 'drink', '16 oz', { cal: 80, protein: 20, satfat: 0.5, carbs: 1, netcarbs: 1, collagen: 14, sodium: 600, potassium: 120, phosphorus: 40, calcium: 15, magnesium: 10, b12: 0.2, folate: 3 }),
  I('berg', 'Dr. Berg electrolytes', 'drink', '1 scoop', { cal: 15, carbs: 3, netcarbs: 2, potassium: 1000, magnesium: 120, calcium: 75, sodium: 40, iron: 0.3 }),
  I('pellegrino', 'San Pellegrino', 'drink', '1 L', { calcium: 150, magnesium: 45, sodium: 31, potassium: 2 }),
  I('egg', 'Egg', 'protein', '1 large', { cal: 72, protein: 6, fat: 5, satfat: 1.6, carbs: 0.4, netcarbs: 0.4, sugar: 0.2, choline: 147, selenium: 15, b7: 10, b2: 0.23, vitA: 80, vitD: 41, b12: 0.55, folate: 22, iodine: 25, phosphorus: 99, calcium: 28, zinc: 0.65, iron: 0.9, b5: 0.7 }),
  I('oysters', 'Oysters', 'protein', '3 oz', { cal: 70, protein: 8, satfat: 0.5, carbs: 4, netcarbs: 4, zinc: 32, copper: 1600, selenium: 64, b12: 16, iron: 5, iodine: 50, omega3: 300, choline: 60 }),
  I('liver', 'Beef liver', 'protein', '3 oz', { cal: 130, protein: 20, satfat: 1.5, carbs: 4, netcarbs: 4, vitA: 6500, copper: 12000, b12: 60, folate: 215, iron: 5, b2: 2.9, choline: 330, selenium: 28, zinc: 4 }),
  I('beef', 'Grass-fed beef', 'protein', '8 oz', { cal: 430, protein: 52, fat: 24, satfat: 10, zinc: 11, iron: 5, b12: 5, b3: 12, selenium: 40, phosphorus: 400, potassium: 600, choline: 150 }),
  I('salmon', 'Wild salmon', 'protein', '6 oz', { cal: 310, protein: 34, fat: 18, satfat: 3, omega3: 3000, vitD: 1000, b12: 5, selenium: 46, b3: 16, potassium: 800, choline: 100 }),
  I('sardines', 'Sardines', 'protein', '1 can', { cal: 190, protein: 23, fat: 11, satfat: 1.5, calcium: 350, omega3: 1000, vitD: 180, b12: 8, selenium: 45, phosphorus: 280 }),
  I('shrimp', 'Shrimp', 'protein', '3 oz', { cal: 85, protein: 20, satfat: 0.1, carbs: 0.2, netcarbs: 0.2, selenium: 34, iodine: 35, copper: 200, b12: 1.4, iron: 0.5, zinc: 1.4 }),
  I('chicken', 'Chicken thigh', 'protein', '4 oz', { cal: 220, protein: 25, fat: 13, satfat: 3.5, b6: 0.4, b3: 7, selenium: 25, zinc: 2, phosphorus: 200, potassium: 250 }),
  I('spinach', 'Spinach', 'veg', '1 cup', { carbs: 1.1, netcarbs: 0.4, sugar: 0.1, fiber: 0.7, vitK: 145, folate: 58, vitA: 140, vitC: 8, magnesium: 24, iron: 0.8, potassium: 167, calcium: 30, manganese: 0.27 }),
  I('broccoli', 'Broccoli', 'veg', '1 cup', { cal: 55, carbs: 11, netcarbs: 6, sugar: 2, vitC: 81, vitK: 92, folate: 57, fiber: 5, calcium: 43, potassium: 290, vitA: 35 }),
  I('kale', 'Kale', 'veg', '1 cup', { carbs: 1.4, netcarbs: 0.5, sugar: 0.2, vitK: 472, vitC: 80, vitA: 170, folate: 19, calcium: 53, manganese: 0.5 }),
  I('bellpepper', 'Bell pepper', 'veg', '1 medium', { cal: 30, carbs: 7, netcarbs: 4.5, sugar: 5, vitC: 152, vitA: 75, folate: 46, b6: 0.4, potassium: 250, fiber: 2.5 }),
  I('sweetpotato', 'Sweet potato', 'veg', '1 medium', { cal: 112, carbs: 26, netcarbs: 22, sugar: 5.4, vitA: 1400, vitC: 22, b6: 0.3, potassium: 440, fiber: 4, manganese: 0.5 }),
  I('avocado', 'Avocado', 'fat', '½', { cal: 160, fat: 15, satfat: 2.1, carbs: 9, netcarbs: 4, sugar: 0.4, fiber: 5, potassium: 345, magnesium: 29, vitE: 2, folate: 60, vitK: 14 }),
  I('blueberries', 'Blueberries', 'fruit', '1 cup', { cal: 85, carbs: 21, netcarbs: 17, sugar: 15, vitC: 14, vitK: 29, fiber: 4, manganese: 0.5 }),
  I('almonds', 'Almonds', 'fat', '1 oz', { cal: 164, protein: 6, fat: 14, satfat: 1.1, carbs: 6, netcarbs: 2.5, sugar: 1.2, vitE: 7, magnesium: 76, calcium: 76, fiber: 3.5 }),
  I('brazilnut', 'Brazil nut', 'fat', '1 nut', { cal: 33, satfat: 0.8, carbs: 0.3, netcarbs: 0.1, sugar: 0.1, selenium: 96, magnesium: 25 }, 'very high selenium'),
  I('oliveoil', 'Olive oil', 'fat', '1 tbsp', { cal: 120, fat: 14, satfat: 1.9, vitE: 2, vitK: 8 }),
  I('kefir', 'Kefir', 'dairy', '1 cup', { cal: 110, protein: 9, satfat: 1.5, carbs: 12, netcarbs: 12, sugar: 11, calcium: 300, b12: 1, phosphorus: 230, potassium: 376 }),
  I('cheese', 'Hard cheese', 'dairy', '1 oz', { cal: 110, protein: 7, satfat: 5.3, carbs: 0.4, netcarbs: 0.4, sugar: 0.1, calcium: 200, fat: 9, b12: 0.4 }),
  I('chickenliver', 'Chicken liver', 'protein', '3 oz', { cal: 142, protein: 21, fat: 6, satfat: 1.9, carbs: 1, netcarbs: 1, vitA: 3980, vitC: 23, b2: 1.5, b3: 9, b5: 5, b6: 0.6, b7: 150, folate: 490, b12: 14, iron: 9, zinc: 3.4, copper: 400, selenium: 70, phosphorus: 340, potassium: 230, choline: 220 }),
  I('beefheart', 'Beef heart', 'protein', '3 oz', { cal: 150, protein: 24, fat: 5, satfat: 1.5, b2: 1.1, b3: 6, b5: 2, b6: 0.3, b12: 11, iron: 6, zinc: 3, copper: 500, selenium: 35, phosphorus: 230, potassium: 210, choline: 135 }),
  I('mackerel', 'Atlantic mackerel', 'protein', '3 oz', { cal: 220, protein: 20, fat: 15, satfat: 3.6, vitD: 340, b12: 16, b3: 6, b6: 0.4, selenium: 44, phosphorus: 236, potassium: 340, magnesium: 83, iron: 1.3, omega3: 1000, choline: 80 }),
  I('cod', 'Cod', 'protein', '3 oz', { cal: 90, protein: 20, fat: 0.7, satfat: 0.1, b12: 1.8, b6: 0.4, selenium: 32, iodine: 99, phosphorus: 117, potassium: 210, omega3: 150 }),
  I('mussels', 'Mussels', 'protein', '3 oz', { cal: 146, protein: 20, fat: 4, satfat: 0.8, carbs: 6, netcarbs: 6, vitC: 12, b2: 0.4, b3: 2.6, b12: 20, folate: 64, iron: 5.7, zinc: 2.3, manganese: 5.8, selenium: 64, phosphorus: 242, potassium: 228, omega3: 700, choline: 65 }),
  I('scallops', 'Scallops', 'protein', '3 oz', { cal: 94, protein: 17, fat: 1.2, satfat: 0.1, carbs: 4, netcarbs: 4, b12: 1.5, phosphorus: 340, potassium: 310, magnesium: 47, selenium: 22, zinc: 1.4, omega3: 300 }),
  I('cauliflower', 'Cauliflower', 'veg', '1 cup', { cal: 27, protein: 2, fat: 0.3, carbs: 5, netcarbs: 3, fiber: 2, sugar: 2, vitC: 52, vitK: 16, folate: 61, b6: 0.2, potassium: 320, choline: 45 }),
  I('zucchini', 'Zucchini', 'veg', '1 cup', { cal: 21, protein: 1.5, fat: 0.4, carbs: 4, netcarbs: 2.6, fiber: 1.4, sugar: 3, vitC: 22, vitA: 24, b6: 0.3, potassium: 325, manganese: 0.2 }),
  I('asparagus', 'Asparagus', 'veg', '1 cup', { cal: 40, protein: 4.3, fat: 0.4, satfat: 0.1, carbs: 7, netcarbs: 3.4, fiber: 3.6, sugar: 2.3, vitK: 91, folate: 268, vitC: 14, vitA: 90, vitE: 2.7, b1: 0.3, iron: 1.6, potassium: 400 }),
  I('brusselssprouts', 'Brussels sprouts', 'veg', '1 cup', { cal: 56, protein: 4, fat: 0.8, satfat: 0.2, carbs: 11, netcarbs: 7, fiber: 4, sugar: 2.7, vitC: 97, vitK: 219, folate: 94, vitA: 60, potassium: 495, manganese: 0.4 }),
  I('cabbage', 'Cabbage', 'veg', '1 cup', { cal: 22, protein: 1.1, fat: 0.1, carbs: 5, netcarbs: 2.8, fiber: 2.2, sugar: 2.8, vitC: 33, vitK: 68, folate: 38, potassium: 150 }),
  I('arugula', 'Arugula', 'veg', '1 cup', { cal: 5, protein: 0.5, fat: 0.1, carbs: 0.7, netcarbs: 0.4, fiber: 0.3, sugar: 0.4, vitK: 22, vitA: 24, folate: 19, vitC: 3, calcium: 32, potassium: 74 }),
  I('mushrooms', 'White mushrooms', 'veg', '1 cup', { cal: 15, protein: 2.2, fat: 0.2, carbs: 2.3, netcarbs: 1.6, fiber: 0.7, sugar: 1.4, vitD: 5, b2: 0.3, b3: 2.5, b5: 1, selenium: 8, copper: 220, potassium: 220 }),
  I('greenbeans', 'Green beans', 'veg', '1 cup', { cal: 44, protein: 2.4, fat: 0.4, satfat: 0.1, carbs: 10, netcarbs: 6, fiber: 4, sugar: 2, vitC: 12, vitK: 60, folate: 42, vitA: 44, potassium: 180, manganese: 0.5 }),
  I('sauerkraut', 'Sauerkraut', 'veg', '½ cup', { cal: 14, protein: 0.7, fat: 0.1, carbs: 3, netcarbs: 1, fiber: 2, sugar: 1.3, vitC: 10, vitK: 9, folate: 12, iron: 1.2, potassium: 120, sodium: 470 }),
  I('kimchi', 'Kimchi', 'veg', '½ cup', { cal: 12, protein: 1, fat: 0.2, carbs: 2, netcarbs: 1, fiber: 1, sugar: 1, vitC: 10, vitK: 24, vitA: 80, folate: 35, potassium: 150, sodium: 500 }, 'sodium varies by recipe'),
  I('yogurt', 'Full-fat plain yogurt', 'dairy', '1 cup', { cal: 150, protein: 8.5, fat: 8, satfat: 5, carbs: 11, netcarbs: 11, sugar: 11, calcium: 296, phosphorus: 233, potassium: 380, b2: 0.3, b12: 1, zinc: 1.4, iodine: 75, choline: 38 }),
  I('macadamia', 'Macadamia nuts', 'fat', '1 oz', { cal: 204, protein: 2.2, fat: 21, satfat: 3.4, carbs: 4, netcarbs: 1.5, fiber: 2.5, sugar: 1.2, b1: 0.3, manganese: 1.2, magnesium: 37, copper: 270, potassium: 104, iron: 1 }),
  I('walnuts', 'Walnuts', 'fat', '1 oz', { cal: 185, protein: 4.3, fat: 18, satfat: 1.7, carbs: 4, netcarbs: 2, fiber: 2, sugar: 0.7, copper: 450, manganese: 1, magnesium: 45, phosphorus: 98, folate: 28 }, 'plant omega-3 (ALA)'),
  I('pecans', 'Pecans', 'fat', '1 oz', { cal: 196, protein: 2.6, fat: 20, satfat: 1.8, carbs: 4, netcarbs: 1.2, fiber: 2.7, sugar: 1.1, manganese: 1.3, copper: 340, zinc: 1.3, magnesium: 34, b1: 0.2 }),
  I('chiaseeds', 'Chia seeds', 'fat', '1 oz', { cal: 138, protein: 5, fat: 9, satfat: 1, carbs: 12, netcarbs: 2, fiber: 10, calcium: 179, magnesium: 95, phosphorus: 244, iron: 2.2, zinc: 1.3, manganese: 0.8 }, 'plant omega-3 (ALA)'),
  I('flaxseeds', 'Ground flaxseed', 'fat', '2 tbsp', { cal: 75, protein: 2.6, fat: 6, satfat: 0.5, carbs: 4, netcarbs: 0.5, fiber: 3.8, sugar: 0.2, magnesium: 55, phosphorus: 90, potassium: 120, b1: 0.2, manganese: 0.4, copper: 170 }, 'plant omega-3 (ALA)'),
  I('hempseeds', 'Hemp seeds (hearts)', 'fat', '3 tbsp', { cal: 166, protein: 9.5, fat: 14.6, satfat: 1.4, carbs: 2.6, netcarbs: 1.4, fiber: 1.2, sugar: 0.4, magnesium: 210, phosphorus: 495, potassium: 360, zinc: 3, iron: 2.4, manganese: 2.75, b1: 0.4, b3: 0.28, calcium: 21, vitE: 0.3, copper: 480 }, 'plant omega-3 (ALA)'),
  I('pumpkinseeds', 'Pumpkin seeds', 'fat', '1 oz', { cal: 151, protein: 7, fat: 13, satfat: 2.3, carbs: 5, netcarbs: 3.2, fiber: 1.8, sugar: 0.4, magnesium: 150, zinc: 2.2, iron: 2.3, phosphorus: 330, manganese: 1.3, copper: 390, potassium: 260 }),
  I('mctoil', 'MCT oil', 'fat', '1 tbsp', { cal: 115, fat: 14, satfat: 14 }),
  I('coconutoil', 'Coconut oil', 'fat', '1 tbsp', { cal: 120, fat: 14, satfat: 12 }),
  I('ghee', 'Ghee', 'fat', '1 tbsp', { cal: 123, fat: 14, satfat: 9, vitA: 108, vitE: 0.4 }),
  I('butter', 'Butter', 'fat', '1 tbsp', { cal: 102, protein: 0.1, fat: 12, satfat: 7, vitA: 97, vitD: 6, vitE: 0.3, vitK: 1 }),
  I('raspberries', 'Raspberries', 'fruit', '1 cup', { cal: 64, protein: 1.5, fat: 0.8, carbs: 15, netcarbs: 7, fiber: 8, sugar: 5, vitC: 32, vitK: 10, folate: 26, manganese: 0.8, magnesium: 27, potassium: 186 }),
  I('strawberries', 'Strawberries', 'fruit', '1 cup', { cal: 53, protein: 1.1, fat: 0.5, carbs: 13, netcarbs: 9.5, fiber: 3.3, sugar: 8, vitC: 98, folate: 40, manganese: 0.6, potassium: 254 }),
  I('blackberries', 'Blackberries', 'fruit', '1 cup', { cal: 62, protein: 2, fat: 0.7, carbs: 14, netcarbs: 6.2, fiber: 7.6, sugar: 7, vitC: 30, vitK: 29, folate: 36, manganese: 0.9, magnesium: 29, potassium: 233 }),
  I('delichicken', 'Sliced deli chicken', 'protein', '2 oz', { cal: 60, protein: 11, fat: 1.5, satfat: 0.4, carbs: 1, netcarbs: 1, sugar: 1, sodium: 500, b3: 5, selenium: 12, phosphorus: 130, potassium: 180 }),
  I('bacon', 'Bacon', 'protein', '2 slices', { cal: 90, protein: 6, fat: 7, satfat: 2.3, carbs: 0.2, netcarbs: 0.2, sodium: 260, selenium: 10, b1: 0.1, b3: 1.5, phosphorus: 60, potassium: 90, zinc: 0.6 }),
  I('groundbeef', 'Ground beef 85/15', 'protein', '4 oz', { cal: 240, protein: 21, fat: 17, satfat: 6.5, zinc: 5, iron: 2.3, b12: 2.5, b3: 5, b6: 0.3, selenium: 18, phosphorus: 175, potassium: 290, choline: 80 }),
  I('ribeye', 'Ribeye steak', 'protein', '6 oz', { cal: 450, protein: 42, fat: 30, satfat: 13, zinc: 8, iron: 2.5, b12: 3, b3: 9, b6: 0.6, selenium: 40, phosphorus: 340, potassium: 540, choline: 130 }),
  I('grouper', 'Grouper', 'protein', '4 oz', { cal: 110, protein: 23, fat: 1.2, satfat: 0.3, b12: 0.7, b6: 0.4, selenium: 45, potassium: 500, phosphorus: 160, magnesium: 36, omega3: 250 }),
  I('snapper', 'Snapper', 'protein', '4 oz', { cal: 120, protein: 24, fat: 1.6, satfat: 0.3, b12: 3.4, b6: 0.5, selenium: 44, potassium: 500, phosphorus: 200, magnesium: 37, omega3: 300 }),
  I('cannedtuna', 'Canned tuna (in water)', 'protein', '1 can (5 oz drained)', { cal: 130, protein: 29, fat: 1.5, satfat: 0.4, selenium: 120, b12: 4, b3: 18, b6: 0.5, vitD: 60, phosphorus: 180, potassium: 340, iron: 1.3, omega3: 250, iodine: 15 }),
  I('chickpeas', 'Chickpeas (cooked)', 'protein', '½ cup', { cal: 135, protein: 7, fat: 2, satfat: 0.2, carbs: 22, netcarbs: 16, fiber: 6, sugar: 4, folate: 141, iron: 2.4, magnesium: 39, phosphorus: 138, potassium: 240, zinc: 1.3, copper: 290, manganese: 0.8 }),
  I('cottagecheese', 'Cottage cheese', 'protein', '½ cup', { cal: 110, protein: 12, fat: 5, satfat: 2.7, carbs: 4, netcarbs: 4, sugar: 3.5, calcium: 100, phosphorus: 150, sodium: 350, b12: 0.7, selenium: 10, b2: 0.2 }),
  I('carrots', 'Carrots', 'veg', '1 cup chopped', { cal: 52, protein: 1.2, fat: 0.3, carbs: 12, netcarbs: 8.4, fiber: 3.6, sugar: 6, vitA: 1070, vitK: 16, vitC: 7, b6: 0.2, potassium: 410, manganese: 0.2 }),
  I('radishes', 'Radishes', 'veg', '1 cup sliced', { cal: 19, protein: 0.8, fat: 0.1, carbs: 4, netcarbs: 2.1, fiber: 1.9, sugar: 2.2, vitC: 17, folate: 29, potassium: 270, calcium: 29 }),
  I('beets', 'Beets', 'veg', '1 cup', { cal: 58, protein: 2.2, fat: 0.2, carbs: 13, netcarbs: 9.2, fiber: 3.8, sugar: 9, folate: 148, potassium: 442, manganese: 0.4, magnesium: 31, vitC: 7 }),
  I('cherrytomatoes', 'Cherry tomatoes', 'veg', '1 cup', { cal: 27, protein: 1.3, fat: 0.3, carbs: 6, netcarbs: 4, fiber: 2, sugar: 4, vitC: 20, vitA: 60, vitK: 12, folate: 22, potassium: 353 }),
  I('redonion', 'Red onion', 'veg', '½ cup chopped', { cal: 32, protein: 0.9, fat: 0.1, carbs: 7.5, netcarbs: 6.4, fiber: 1.1, sugar: 3.4, vitC: 6, b6: 0.1, folate: 15, potassium: 116 }),
  I('celery', 'Celery', 'veg', '1 cup chopped', { cal: 16, protein: 0.7, fat: 0.2, carbs: 3, netcarbs: 1.4, fiber: 1.6, sugar: 1.8, vitK: 30, folate: 36, potassium: 260, vitC: 3, sodium: 88 }),
  I('cucumber', 'Cucumber', 'veg', '1 cup sliced', { cal: 16, protein: 0.7, fat: 0.1, carbs: 3.8, netcarbs: 3.3, fiber: 0.5, sugar: 1.7, vitK: 17, vitC: 3, potassium: 152 }),
  I('swisschard', 'Swiss chard', 'veg', '1 cup', { cal: 7, protein: 0.6, fat: 0.1, carbs: 1.4, netcarbs: 0.8, fiber: 0.6, vitK: 298, vitA: 110, vitC: 11, magnesium: 29, potassium: 136, iron: 0.6 }),
  I('bokchoy', 'Bok choy', 'veg', '1 cup', { cal: 9, protein: 1, fat: 0.1, carbs: 1.5, netcarbs: 0.8, fiber: 0.7, sugar: 0.8, vitA: 156, vitC: 31, vitK: 32, folate: 46, potassium: 176, calcium: 74 }),
  I('garlic', 'Garlic', 'veg', '1 clove', { cal: 4, protein: 0.2, carbs: 1, netcarbs: 0.9, fiber: 0.1, vitC: 0.9, manganese: 0.05, selenium: 0.4 }),
  I('jalapenos', 'Jalapeños', 'veg', '1 pepper', { cal: 4, protein: 0.1, fat: 0.1, carbs: 0.9, netcarbs: 0.5, fiber: 0.4, sugar: 0.6, vitC: 10, vitA: 6, b6: 0.1 }),
  I('lettuce', 'Shredded lettuce', 'veg', '1 cup', { cal: 5, protein: 0.5, carbs: 1, netcarbs: 0.4, fiber: 0.6, sugar: 0.4, vitK: 48, vitA: 74, folate: 21, potassium: 70 }),
  I('cilantro', 'Cilantro', 'veg', '¼ cup', { cal: 1, carbs: 0.1, netcarbs: 0.1, vitK: 12, vitA: 17, vitC: 1, potassium: 20 }),
  I('ginger', 'Ginger', 'veg', '1 tbsp grated', { cal: 5, protein: 0.1, carbs: 1.1, netcarbs: 0.9, fiber: 0.1, sugar: 0.1, potassium: 25, magnesium: 3, manganese: 0.13 }),
  I('lemon', 'Lemon', 'fruit', '1 medium', { cal: 17, protein: 0.6, carbs: 5.4, netcarbs: 3.8, fiber: 1.6, sugar: 1.5, vitC: 31, potassium: 116, folate: 9 }),
  I('lime', 'Lime', 'fruit', '1 medium', { cal: 20, protein: 0.5, carbs: 7, netcarbs: 5.1, fiber: 1.9, sugar: 1.1, vitC: 19, potassium: 68, folate: 5 }),
  I('pineapple', 'Pineapple', 'fruit', '1 cup chunks', { cal: 82, protein: 0.9, fat: 0.2, carbs: 22, netcarbs: 19.7, fiber: 2.3, sugar: 16, vitC: 79, manganese: 1.5, b6: 0.2, folate: 30, potassium: 180 }),
  I('apple', 'Apple', 'fruit', '1 medium', { cal: 95, protein: 0.5, fat: 0.3, carbs: 25, netcarbs: 20.6, fiber: 4.4, sugar: 19, vitC: 8, potassium: 195, vitK: 4 }),
  I('clementine', 'Clementine', 'fruit', '1 fruit', { cal: 35, protein: 0.6, carbs: 9, netcarbs: 7.7, fiber: 1.3, sugar: 7, vitC: 36, folate: 24, potassium: 131 }),
  I('plumcot', 'Plumcot', 'fruit', '1 fruit', { cal: 76, protein: 1, fat: 0.2, carbs: 19, netcarbs: 17, fiber: 2, sugar: 16, vitC: 16, potassium: 200, vitA: 30 }),
  I('driedcranberries', 'Dried cranberries', 'fruit', '¼ cup', { cal: 123, protein: 0.1, fat: 0.5, carbs: 33, netcarbs: 30.5, fiber: 2.5, sugar: 26, vitC: 0.2, vitE: 1, manganese: 0.1 }, 'sweetened; high sugar'),
  I('banana', 'Banana', 'fruit', '1 medium', { cal: 105, protein: 1.3, fat: 0.4, carbs: 27, netcarbs: 23.9, fiber: 3.1, sugar: 14, vitC: 10, b6: 0.4, potassium: 422, magnesium: 32, manganese: 0.3 }),
  I('cherries', 'Cherries', 'fruit', '1 cup', { cal: 87, protein: 1.5, fat: 0.3, carbs: 22, netcarbs: 19, fiber: 3, sugar: 18, vitC: 10, potassium: 342, copper: 95, manganese: 0.1 }),
  I('feta', 'Feta', 'dairy', '1 oz', { cal: 75, protein: 4, fat: 6, satfat: 4.2, carbs: 1.2, netcarbs: 1.2, sugar: 1.2, calcium: 140, sodium: 320, phosphorus: 95, b12: 0.5, b2: 0.2 }),
  I('goatcheese', 'Goat cheese', 'dairy', '1 oz', { cal: 75, protein: 5, fat: 6, satfat: 4.1, carbs: 0.3, netcarbs: 0.3, calcium: 40, phosphorus: 73, vitA: 115, sodium: 130, iron: 0.5 }),
  I('cheddar', 'Shredded cheddar', 'dairy', '¼ cup', { cal: 110, protein: 7, fat: 9, satfat: 5.3, carbs: 0.9, netcarbs: 0.9, sugar: 0.1, calcium: 200, phosphorus: 145, sodium: 180, b12: 0.3, vitA: 75, zinc: 0.9 }),
  I('wholemilk', 'Whole milk', 'dairy', '1 cup', { cal: 149, protein: 8, fat: 8, satfat: 4.6, carbs: 12, netcarbs: 12, sugar: 12, calcium: 276, phosphorus: 205, potassium: 322, b12: 1.1, b2: 0.4, vitD: 124, vitA: 112, iodine: 85, choline: 43 }),
  I('sourcream', 'Sour cream', 'dairy', '2 tbsp', { cal: 60, protein: 0.7, fat: 6, satfat: 3.5, carbs: 1, netcarbs: 1, sugar: 0.8, calcium: 30, vitA: 55, phosphorus: 20 }),
  I('cashews', 'Cashews', 'fat', '1 oz', { cal: 157, protein: 5, fat: 12, satfat: 2.2, carbs: 9, netcarbs: 8, fiber: 1, sugar: 1.7, copper: 620, magnesium: 83, phosphorus: 168, zinc: 1.6, iron: 1.9, manganese: 0.5, vitK: 9.7 }),
  I('almondbutter', 'Almond butter', 'fat', '2 tbsp', { cal: 196, protein: 7, fat: 18, satfat: 1.4, carbs: 6, netcarbs: 3, fiber: 3, sugar: 1.4, vitE: 8, magnesium: 89, calcium: 111, potassium: 240, manganese: 0.9, phosphorus: 160 }),
  I('peanutbutter', 'Peanut butter', 'fat', '2 tbsp', { cal: 190, protein: 7, fat: 16, satfat: 3.3, carbs: 7, netcarbs: 5, fiber: 2, sugar: 3, b3: 4.3, vitE: 3, magnesium: 54, phosphorus: 107, potassium: 208, folate: 24 }),
  I('pbpowder', 'PB powder', 'fat', '2 tbsp', { cal: 60, protein: 8, fat: 2, satfat: 0.4, carbs: 6, netcarbs: 4, fiber: 2, sugar: 2, b3: 4, magnesium: 50, potassium: 300, phosphorus: 90 }),
  I('cacaopowder', 'Cacao powder', 'fat', '1 tbsp', { cal: 25, protein: 1, fat: 1.5, satfat: 0.9, carbs: 3, netcarbs: 1, fiber: 2, magnesium: 27, iron: 0.8, copper: 200, manganese: 0.2, potassium: 82 }),
  I('cacaonibs', 'Cacao nibs', 'fat', '1 tbsp', { cal: 65, protein: 1.5, fat: 5, satfat: 3, carbs: 3, netcarbs: 1, fiber: 2, magnesium: 30, iron: 1, copper: 200, manganese: 0.3 }),
  I('nutzo', 'Nutzo mixed nut butter', 'fat', '2 tbsp', { cal: 180, protein: 6, fat: 15, satfat: 2, carbs: 8, netcarbs: 5, fiber: 3, sugar: 1, magnesium: 70, iron: 1.5, potassium: 180, vitE: 3, copper: 300 }),
  I('maca', 'Maca powder', 'fat', '1 tsp', { cal: 10, protein: 0.5, fat: 0.1, carbs: 2, netcarbs: 1.6, fiber: 0.4, sugar: 1, vitC: 2, iron: 0.5, copper: 100, potassium: 60 }, 'low-confidence; label varies'),
  I('avocadooil', 'Avocado oil', 'fat', '1 tbsp', { cal: 124, fat: 14, satfat: 1.6, vitE: 3.5 }),
  I('sesameoil', 'Sesame oil', 'fat', '1 tbsp', { cal: 120, fat: 14, satfat: 2, vitK: 1.8, vitE: 0.2 }),
  I('tallow', 'Beef tallow', 'fat', '1 tbsp', { cal: 115, fat: 13, satfat: 6.4, vitE: 0.4 }),
  I('coffee', 'Coffee (black)', 'drink', '1 cup', { cal: 2, potassium: 116, magnesium: 7, b3: 0.5 }),
  I('coconutmilk', 'Coconut milk (canned)', 'drink', '½ cup', { cal: 220, protein: 2, fat: 24, satfat: 21, carbs: 3, netcarbs: 3, sugar: 2, iron: 1.9, magnesium: 45, potassium: 315, manganese: 0.9, copper: 200 }),
  I('almondmilk', 'Almond milk (unsweetened)', 'drink', '1 cup', { cal: 30, protein: 1, fat: 2.5, satfat: 0.2, carbs: 1, netcarbs: 1, sugar: 0, calcium: 450, vitE: 6.3, vitD: 100, vitA: 150, magnesium: 16 }),
  I('wheyprotein', 'Whey protein', 'drink', '1 scoop', { cal: 120, protein: 24, fat: 1.5, satfat: 0.5, carbs: 3, netcarbs: 2, sugar: 2, calcium: 130, sodium: 60, potassium: 160 }),
  I('greenlentils', 'Green lentils (cooked)', 'extra', '½ cup', { cal: 115, protein: 9, fat: 0.4, carbs: 20, netcarbs: 12, fiber: 8, sugar: 1.8, folate: 179, iron: 3.3, magnesium: 36, phosphorus: 178, potassium: 365, zinc: 1.3, manganese: 0.5, b1: 0.2 }),
  I('whiterice', 'Cilantro-lime rice (white)', 'extra', '½ cup cooked', { cal: 120, protein: 2.2, fat: 1, satfat: 0.2, carbs: 26, netcarbs: 25.6, fiber: 0.4, folate: 46, manganese: 0.4, b1: 0.1, iron: 1 }),
  I('tortilla', 'Grain-free tortilla (almond)', 'extra', '1 tortilla', { cal: 90, protein: 3, fat: 5, satfat: 0.5, carbs: 10, netcarbs: 7, fiber: 3, sugar: 0, sodium: 190, calcium: 40, vitE: 2 }),
  I('croutons', 'Croutons', 'extra', '¼ cup', { cal: 45, protein: 1.3, fat: 1.7, satfat: 0.3, carbs: 6, netcarbs: 5.5, fiber: 0.5, sugar: 0.5, sodium: 100 }),
  I('ketogranola', 'Keto granola', 'extra', '¼ cup', { cal: 160, protein: 6, fat: 13, satfat: 3, carbs: 10, netcarbs: 4, fiber: 6, sugar: 1, magnesium: 60, calcium: 40, iron: 1.2 }),
  I('kalamata', 'Kalamata olives', 'extra', '5 olives', { cal: 45, protein: 0.3, fat: 4.5, satfat: 0.6, carbs: 2.5, netcarbs: 1.3, fiber: 1.2, sodium: 330, iron: 0.5, vitE: 0.5, copper: 60 }),
  I('cassavaflour', 'Cassava flour', 'extra', '¼ cup', { cal: 114, protein: 0.7, fat: 0.2, carbs: 28, netcarbs: 26, fiber: 2, sugar: 1, calcium: 5, iron: 0.4, potassium: 75 }),
  I('coconutflour', 'Coconut flour', 'extra', '2 tbsp', { cal: 60, protein: 2, fat: 2, satfat: 1.7, carbs: 8, netcarbs: 3, fiber: 5, sugar: 2, iron: 1, potassium: 120 }),
  I('coconutsugar', 'Coconut sugar', 'extra', '1 tsp', { cal: 15, carbs: 4, netcarbs: 4, sugar: 4, potassium: 12 }),
  I('monkfruit', 'Monkfruit sweetener', 'extra', '1 tsp', { cal: 0, carbs: 0, netcarbs: 0, sugar: 0 }, 'erythritol-blend; 0 net'),
  I('shreddedcoconut', 'Shredded coconut (unsweetened)', 'extra', '2 tbsp', { cal: 70, protein: 0.7, fat: 6.6, satfat: 5.9, carbs: 2.5, netcarbs: 0.8, fiber: 1.7, sugar: 1, manganese: 0.4, copper: 60, iron: 0.4 }),
  I('bakingsoda', 'Baking soda', 'extra', '1 tsp', { cal: 0, carbs: 0, netcarbs: 0, sodium: 1259 }, 'sodium only'),
  I('ranch', 'Ranch dressing', 'extra', '1 tbsp', { cal: 65, protein: 0.2, fat: 7, satfat: 1, carbs: 0.8, netcarbs: 0.8, sugar: 0.6, sodium: 135 }),
  I('caesar', 'Caesar dressing', 'extra', '1 tbsp', { cal: 78, protein: 0.5, fat: 8.5, satfat: 1.3, carbs: 0.5, netcarbs: 0.5, sugar: 0.4, sodium: 160 }),
  I('balsamic', 'Balsamic vinaigrette', 'extra', '1 tbsp', { cal: 45, fat: 4, satfat: 0.6, carbs: 2, netcarbs: 2, sugar: 2, sodium: 120 }),
  I('tzatziki', 'Tzatziki', 'extra', '2 tbsp', { cal: 30, protein: 1.5, fat: 2, satfat: 1, carbs: 1.5, netcarbs: 1.5, sugar: 1, calcium: 30, sodium: 90 }),
  I('tahini', 'Tahini', 'extra', '1 tbsp', { cal: 89, protein: 2.6, fat: 8, satfat: 1.1, carbs: 3, netcarbs: 2, fiber: 1.4, sugar: 0.1, calcium: 64, iron: 1.3, magnesium: 14, phosphorus: 110, copper: 240 }),
  I('mayo', 'Mayo', 'extra', '1 tbsp', { cal: 94, protein: 0.1, fat: 10, satfat: 1.6, carbs: 0.1, netcarbs: 0.1, sugar: 0.1, vitE: 1.2, vitK: 24 }),
  I('salsa', 'Salsa', 'extra', '2 tbsp', { cal: 10, protein: 0.4, fat: 0.1, carbs: 2, netcarbs: 1.5, fiber: 0.5, sugar: 1, sodium: 200, vitC: 2, potassium: 80 }),
  I('salsaverde', 'Salsa verde', 'extra', '2 tbsp', { cal: 15, protein: 0.3, fat: 0.4, carbs: 2.5, netcarbs: 2, fiber: 0.5, sugar: 1.4, sodium: 190, vitC: 4 }),
  I('honey', 'Honey', 'extra', '1 tbsp', { cal: 64, carbs: 17, netcarbs: 17, sugar: 17 }),
  I('maplesyrup', 'Maple syrup', 'extra', '1 tbsp', { cal: 52, carbs: 13, netcarbs: 13, sugar: 12, manganese: 0.5, calcium: 20 }),
  I('mustard', 'Mustard', 'extra', '1 tsp', { cal: 3, protein: 0.2, fat: 0.2, carbs: 0.3, netcarbs: 0.1, fiber: 0.2, sodium: 55, selenium: 3 }),
  I('ketchup', 'Ketchup', 'extra', '1 tbsp', { cal: 17, protein: 0.2, carbs: 4.5, netcarbs: 4.4, fiber: 0.1, sugar: 3.7, sodium: 154, potassium: 57 }),
  I('buffalosauce', 'Buffalo sauce', 'extra', '1 tbsp', { cal: 15, fat: 1.2, carbs: 0.5, netcarbs: 0.5, sodium: 460, vitC: 1 }),
  I('crema', 'Cilantro-lime crema', 'extra', '1 tbsp', { cal: 50, protein: 0.5, fat: 5, satfat: 1.5, carbs: 1, netcarbs: 1, sugar: 0.8, sodium: 75 }, 'low-confidence; recipe varies'),
  I('teriyaki', 'Teriyaki sauce', 'extra', '1 tbsp', { cal: 15, protein: 1, carbs: 3, netcarbs: 3, sugar: 2.5, sodium: 610 }),
  I('garlicchili', 'Garlic chili sauce', 'extra', '1 tbsp', { cal: 15, protein: 0.3, carbs: 3, netcarbs: 2.7, fiber: 0.3, sugar: 2, sodium: 280, vitC: 3 }),
  I('coconutaminos', 'Coconut aminos', 'extra', '1 tbsp', { cal: 10, carbs: 1, netcarbs: 1, sugar: 1, sodium: 90, potassium: 30 }),
  I('coconutsyrup', 'Coconut syrup', 'extra', '1 tbsp', { cal: 45, carbs: 11, netcarbs: 11, sugar: 9, potassium: 15 }, 'low-confidence; label varies'),
  I('tacoseasoning', 'Taco seasoning', 'extra', '1 tbsp', { cal: 20, protein: 0.8, fat: 0.5, carbs: 4, netcarbs: 3, fiber: 1, sugar: 0.5, sodium: 410, iron: 0.8, vitA: 40 }),
  I('hotsauce', 'Hot sauce', 'extra', '1 tsp', { cal: 1, carbs: 0.1, netcarbs: 0.1, sodium: 125, vitC: 1 }),
  I('pastasauce', 'Pasta sauce (marinara)', 'extra', '½ cup', { cal: 70, protein: 2, fat: 2, satfat: 0.3, carbs: 10, netcarbs: 7, fiber: 3, sugar: 7, sodium: 480, vitA: 40, vitC: 8, potassium: 400, iron: 1 }),
  I('cocktailsauce', 'Cocktail sauce', 'extra', '2 tbsp', { cal: 30, protein: 0.4, carbs: 7, netcarbs: 6.5, fiber: 0.5, sugar: 5, sodium: 340, vitC: 3 }),
  I('pickles', 'Pickles', 'extra', '1 spear', { cal: 4, protein: 0.2, carbs: 0.8, netcarbs: 0.5, fiber: 0.3, sugar: 0.4, sodium: 280, vitK: 15 }),
  I('chocchips', 'Chocolate chips', 'extra', '1 tbsp', { cal: 70, protein: 0.6, fat: 4, satfat: 2.5, carbs: 9, netcarbs: 8, fiber: 1, sugar: 8, iron: 0.9, magnesium: 12 }),
  I('salt', 'Salt', 'extra', 'pinch', { sodium: 300 }),
];

export const STACK = [
  I('multi', 'Thorne Basic Nutrients 2/Day', 'sup', 'multivitamin', { vitA: 1050, vitC: 250, vitD: 2000, vitE: 16.5, vitK: 400, b1: 50, b2: 12, b3: 20, b5: 90, b6: 10, b7: 400, folate: 400, b12: 3, zinc: 15, copper: 450, selenium: 200, iodine: 225, manganese: 2, chromium: 100, calcium: 52, magnesium: 40 }),
  I('dake', 'Suppgrade DAKE (D/A/K/E)', 'sup', 'fat-solubles', { vitD: 5000, vitA: 1515, vitE: 50, vitK: 300 }),
  I('omega', 'Omega 2000 fish oil', 'sup', '875 DHA', { omega3: 2000 }),
  I('bufferedc', 'Buffered Vitamin C', 'sup', 'Integrative', { vitC: 500 }),
  I('puremelt', 'PureMelt B12 + Folate', 'sup', 'Pure Encaps', { carbs: 0.5, netcarbs: 0.5, sugar: 0.5, folate: 400, b12: 1000 }),
  I('rhomag', 'Magnesium (Rho)', 'sup', '1 dose', { magnesium: 300 }),
  I('chromium', 'Chromium picolinate', 'sup', '1 dose', { chromium: 200 }),
  I('neurotopical', 'Methylation Pro Topical', 'sup', 'Neuro Biologix', {}, 'methylation support'),
  I('fatty15', 'Fatty15 (C15:0)', 'sup', '1 cap', {}, 'no charted nutrients'),
  I('glycine', 'Glycine', 'sup', 'Pure Encaps', {}, 'no charted nutrients'),
  I('nac', 'NAC 500mg', 'sup', 'Seeking Health', {}, 'no charted nutrients'),
  I('ubqh', 'UBQH / CoQ10 100mg', 'sup', 'Integrative', {}, 'no charted nutrients'),
  I('lithium', 'Lithium orotate 5mg', 'sup', 'Vital Nutrients', {}, 'no charted nutrients'),
  I('p3om', 'P3-OM probiotic', 'sup', 'BiOptimizers', {}, 'no charted nutrients'),
  I('regenx', 'REGEN-X', 'sup', 'PureLife', {}, 'no charted nutrients'),
];

const RECIPES = {
  breakfast: {
    ingredients: ['2 eggs', 'Spinach — a handful', 'Sea salt — a pinch'],
    steps: ['Cook the eggs (scrambled or fried) with the spinach.', 'Season with a pinch of salt.'],
  },
  tuna: {
    ingredients: ['Tuna — 1 can (~5 oz), drained', 'Celery — 1 stalk, chopped', 'Mayonnaise — ~2 tbsp'],
    steps: ['Mix everything together.'],
  },
  quinoa: {
    ingredients: ['Cooked quinoa — ¾ cup', 'Arugula — a handful', 'Tomato — ⅓, chopped', 'Olive oil — ~1 tbsp'],
    steps: ['Toss the quinoa with the arugula and tomato.', 'Dress with olive oil.'],
  },
  kwaffle: {
    makes: 'Makes 4 waffles',
    ingredients: ['Almond flour — 2 cups (200 g)', 'Eggs — 4 large', 'Butter or ghee — ¼ cup, melted', 'Milk — ¼ cup', 'Baking powder — 2 tsp', 'Vanilla — 1 tsp', 'Sea salt — ¼ tsp'],
    steps: ['Whisk the eggs, melted butter, milk, and vanilla.', 'Stir in the almond flour, baking powder, and salt until smooth.', 'Cook in a waffle iron. Makes 4.'],
  },
  cwaffle: {
    makes: 'Makes 4 waffles',
    ingredients: ['Coconut flour — ½ cup', 'Eggs — 6 large', 'Butter, ghee, or coconut oil — ¼ cup, melted', 'Coconut milk (or heavy cream) — ½ cup', 'Baking powder — 1½ tsp', 'Vanilla — 1 tsp', 'Sea salt — ¼ tsp'],
    steps: ['Whisk the eggs, melted butter, coconut milk, and vanilla.', 'Stir in the coconut flour, baking powder, and salt; let it sit 2–3 min to thicken.', 'Cook in a waffle iron. Makes 4.'],
  },
};
LIB.forEach((m) => { if (RECIPES[m.id]) m.recipe = RECIPES[m.id]; });

export const ALLMAP = {};
[...LIB, ...STACK].forEach((it) => { ALLMAP[it.id] = it; });

// Standard daily dose per supplement (units + word). Nutrients scale by (taken / caps).
export const DOSE = {
  multi: { caps: 2, unit: 'capsules' },
  dake: { caps: 1, unit: 'capsules' },
  omega: { caps: 2, unit: 'softgels' },
  bufferedc: { caps: 1, unit: 'capsule' },
  puremelt: { caps: 1, unit: 'melt' },
  rhomag: { caps: 1, unit: 'capsule' },
  chromium: { caps: 1, unit: 'capsule' },
  neurotopical: { caps: 1, unit: 'topical' },
  fatty15: { caps: 1, unit: 'capsule' },
  glycine: { caps: 1, unit: 'capsule' },
  nac: { caps: 1, unit: 'capsule' },
  ubqh: { caps: 1, unit: 'softgel' },
  lithium: { caps: 1, unit: 'capsule' },
  p3om: { caps: 2, unit: 'capsules' },
  regenx: { caps: 1, unit: 'drops' },
};

// Grocery list. '*' suffix = on Kim's default list. Not tied to nutrients.
const GRAW = [
  ['Salad bar', ['Quinoa*', 'Carrots', 'Croutons', 'Kalamata olives*', 'Feta', 'Red onion*', 'Radishes', 'Beets', 'Bell peppers', 'Cherry tomatoes*', 'Dried cranberries*', 'Pumpkin seeds*']],
  ['Salad dressing', ['Ranch*', 'Balsamic*', 'Caesar']],
  ['Protein bar', ['Tuna (celery & mayo)*', 'Sliced chicken*', 'Plain quinoa*', 'Quinoa salad (cilantro, mint)', 'Bacon', 'Hard boiled eggs', 'Ground meat*', 'Chickpeas*', 'Steak', 'Cottage cheese']],
  ['Taco bar', ['Avocado', 'Shredded cheese', 'Salsa', 'Sour cream', 'Jalapeños', 'Cilantro', 'Lime wedges*', 'Hot sauce', 'Shredded lettuce', 'Tortillas*']],
  ['Yogurt & fruit', ['Yogurt', 'Keto granola*', 'Pineapple*', 'Blueberries*', 'Blackberries', 'Raspberries']],
  ['Smoothie bar (freezer)', ['Frozen blueberries*', 'Frozen cherries*', 'Frozen bananas', 'Frozen pineapple*', 'Frozen beet roots*']],
  ['Fish bar', ['Salmon*', 'Shrimp', 'Grouper*', 'Snapper', 'Oysters']],
  ['Veggie bar', ['Baby spinach*', 'Swiss chard', 'Broccoli', 'Brussels sprouts*', 'Kale', 'Bok choy']],
  ['Dairy bar', ['Kefir', 'Milk', 'Goat cheese']],
  ['Juicing', ['Lemon*', 'Ginger*', 'Celery', 'Cucumber', 'Beets', 'Carrots']],
  ['Snack bar', ['Chocolate chips', 'Pickles*', 'Clementines', 'Apples*', 'Plumcots', 'Almond butter*', 'Peanut butter*', 'Cacao*', 'Maca', 'PB powder*', 'Cacao nibs*', 'Nutzo*']],
  ['Condiments & extras', ['Tzatziki*', 'Tahini*', 'Mayo*', 'Salsa verde*', 'Honey*', 'Maple syrup*', 'Ghee*', 'Mustard*', 'Ketchup*', 'Buffalo sauce*', 'Cilantro lime crema*', 'Balsamic glaze*', 'Olive oil*', 'Avocado oil*', 'Balsamic vinaigrette*', 'Beef tallow*', 'Sauerkraut', 'Cocktail sauce', 'Pasta sauce*', 'Teriyaki*', 'Garlic chili*', 'Grass fed butter*', 'Coco aminos*', 'Coconut syrup*', 'Sesame oil*', 'Taco seasoning*']],
  ['Pantry', ['Protein powder*', 'Coconut milk', 'Almond milk*', 'Bone broth*', 'Coffee*', 'Cilantro lime rice*', 'Green lentils*', 'Garlic*', 'Sweet potatoes*']],
  ['Baking', ['Cassava flour*', 'Coconut flour*', 'Coconut sugar*', 'Almond flour*', 'Baking soda*', 'Shredded coconut*', 'Monkfruit*']],
  ['Nuts & seeds', ['Macadamia nuts', 'Cashews*', 'Chia seeds*', 'Flax seeds']],
];
const gslug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '');
export const GROCERY_CATS = GRAW.map(([cat, arr]) => ({
  cat,
  items: arr.map((raw) => {
    const def = raw.endsWith('*');
    const name = def ? raw.slice(0, -1) : raw;
    return { id: gslug(cat) + '-' + gslug(name), name, def };
  }),
}));
// Grocery list starts empty — you build it by tapping Pantry items you need.
export const GROCERY_DEFAULTS = {};

// Plate food list grouped like the grocery list (each food has one home).
export const PLATE_SECTIONS = [
  ['Meals', ['breakfast', 'tuna', 'quinoa', 'kwaffle', 'cwaffle']],
  ['Fish bar', ['oysters', 'salmon', 'sardines', 'shrimp', 'mackerel', 'cod', 'mussels', 'scallops', 'grouper', 'snapper', 'cannedtuna']],
  ['Protein bar', ['egg', 'liver', 'beef', 'chicken', 'chickenliver', 'beefheart', 'delichicken', 'bacon', 'groundbeef', 'ribeye', 'chickpeas', 'cottagecheese']],
  ['Veggie bar', ['spinach', 'broccoli', 'kale', 'sweetpotato', 'cauliflower', 'zucchini', 'asparagus', 'brusselssprouts', 'cabbage', 'arugula', 'mushrooms', 'greenbeans', 'sauerkraut', 'kimchi', 'swisschard', 'bokchoy']],
  ['Salad bar', ['bellpepper', 'carrots', 'radishes', 'beets', 'cherrytomatoes', 'redonion', 'celery', 'cucumber', 'pumpkinseeds', 'driedcranberries', 'feta', 'croutons', 'kalamata']],
  ['Taco bar', ['avocado', 'cheddar', 'sourcream', 'salsa', 'hotsauce', 'jalapenos', 'cilantro', 'lettuce', 'lime', 'tortilla']],
  ['Yogurt & fruit', ['yogurt', 'blueberries', 'raspberries', 'strawberries', 'blackberries', 'lemon', 'pineapple', 'apple', 'clementine', 'plumcot', 'banana', 'cherries', 'ketogranola']],
  ['Dairy bar', ['kefir', 'cheese', 'goatcheese', 'wholemilk']],
  ['Nuts & seeds', ['almonds', 'brazilnut', 'macadamia', 'walnuts', 'pecans', 'chiaseeds', 'flaxseeds', 'hempseeds', 'cashews']],
  ['Snack bar', ['almondbutter', 'peanutbutter', 'pbpowder', 'cacaopowder', 'cacaonibs', 'nutzo', 'maca', 'pickles', 'chocchips']],
  ['Condiments & extras', ['oliveoil', 'avocadooil', 'sesameoil', 'mctoil', 'coconutoil', 'ghee', 'butter', 'tallow', 'ranch', 'caesar', 'balsamic', 'tzatziki', 'tahini', 'mayo', 'salsaverde', 'honey', 'maplesyrup', 'mustard', 'ketchup', 'buffalosauce', 'crema', 'teriyaki', 'garlicchili', 'coconutaminos', 'coconutsyrup', 'tacoseasoning', 'pastasauce', 'cocktailsauce', 'salt']],
  ['Pantry', ['greenlentils', 'whiterice', 'garlic', 'ginger']],
  ['Baking', ['cassavaflour', 'coconutflour', 'coconutsugar', 'monkfruit', 'shreddedcoconut', 'bakingsoda']],
  ['Drinks', ['matcha', 'beam', 'thorneamino', 'broth', 'berg', 'pellegrino', 'coffee', 'coconutmilk', 'almondmilk', 'wheyprotein']],
];
export const PLATE_SECTION_ORDER = PLATE_SECTIONS.map((s) => s[0]).concat(['Your custom items']);
export const SEC_OF = {};
PLATE_SECTIONS.forEach(([sec, ids]) => ids.forEach((id) => { SEC_OF[id] = sec; }));

export const MOOD_LEVELS = [
  { id: 'sinking', label: 'Sinking', color: '#3D5CA8', med: '#C6CFEA' },
  { id: 'low', label: 'Heavy', color: '#7E92D8', med: '#D9DFF4' },
  { id: 'level', label: 'Even', color: '#2FA97C', med: '#BFE6D3' },
  { id: 'lifted', label: 'Rising', color: '#E2A02C', med: '#F2E0AC' },
  { id: 'racing', label: 'Racing', color: '#DA5348', med: '#F3CBC4' },
];
export const MOOD_MAP = Object.fromEntries(MOOD_LEVELS.map((m) => [m.id, m]));

export const ENERGY_LEVELS = [
  { id: 'low', label: 'Running low' },
  { id: 'steady', label: 'Steady' },
  { id: 'buzzing', label: 'Buzzing' },
];

export const SLEEP_HRS = [
  { id: 'u4', label: 'Under 4' },
  { id: '4_6', label: '4–6' },
  { id: '6_8', label: '6–8' },
  { id: '8p', label: '8+' },
];
export const SLEEP_FELT = [
  { id: 'rested', label: 'Rested' },
  { id: 'deep', label: 'Deep' },
  { id: 'light', label: 'Light' },
  { id: 'restless', label: 'Restless' },
  { id: 'woke', label: 'Woke a lot' },
  { id: 'wired', label: 'Wired' },
  { id: 'couldnt', label: "Couldn't wind down" },
  { id: 'groggy', label: 'Groggy' },
  { id: 'dreams', label: 'Vivid dreams' },
];

export const TANK_LEVELS = [
  { id: 'roomy', label: 'Roomy' },
  { id: 'full', label: 'Full' },
  { id: 'toomuch', label: 'Too much' },
];

export const MOODS = [
  { id: 'calm', label: 'Calm' },
  { id: 'grounded', label: 'Grounded' },
  { id: 'connected', label: 'Connected' },
  { id: 'content', label: 'Content' },
  { id: 'clear', label: 'Clear' },
  { id: 'good', label: 'Good' },
  { id: 'hopeful', label: 'Hopeful' },
  { id: 'numb', label: 'Numb' },
  { id: 'anxious', label: 'Anxious' },
  { id: 'irritable', label: 'Irritable' },
  { id: 'overwhelmed', label: 'Overwhelmed' },
  { id: 'foggy', label: 'Foggy' },
  { id: 'restless', label: 'Restless' },
];

export const HABITS = [
  { id: 'sun_am', label: 'Morning sunlight', grp: 'daily', cat: 'Light & sun' },
  { id: 'sun_pm', label: 'Afternoon sunlight', grp: 'daily', cat: 'Light & sun' },
  { id: 'sunset', label: 'Sunset', grp: 'daily', cat: 'Light & sun' },
  { id: 'redlight', label: 'Red light', grp: 'daily', cat: 'Light & sun' },
  { id: 'sauna', label: 'Sauna', grp: 'daily', cat: 'Cold & heat' },
  { id: 'cold_plunge', label: 'Cold plunge', grp: 'daily', cat: 'Cold & heat' },
  { id: 'yoga', label: 'Yoga', grp: 'daily', cat: 'Movement' },
  { id: 'swimming', label: 'Swimming', grp: 'daily', cat: 'Movement' },
  { id: 'grounding', label: 'Grounding', grp: 'daily', cat: 'Grounding & mind' },
  { id: 'journal', label: 'Aesthetic journaling', grp: 'daily', cat: 'Grounding & mind' },
  { id: 'no_toxins', label: 'No toxic chemicals', grp: 'daily', cat: 'Body care' },
  { id: 'floss', label: 'Flossing', grp: 'daily', cat: 'Body care' },
  { id: 'waterpik', label: 'Water pick', grp: 'daily', cat: 'Body care' },
  { id: 'labs', label: 'Labs', note: 'once a year', grp: 'occasional' },
  { id: 'hair_color', label: 'Hair coloring', note: '3–4× a year', grp: 'occasional' },
];
